package de.dreambeam.veusz.format

object Colors  {
  val Foreground = "foreground"
  val Background = "background"
  val Transparent = "transparent"
  val Auto = "auto"
  val White = "white"
  val Black = "black"
  val Red = "red"
  val Green = "green"
  val Blue = "blue"
  val Cyan = "cyan"
  val Magenta = "magenta"
  val Yellow = "yellow"
  val Grey = "grey"
  val DarkRed = "darkred"
  val DarkGreen = "darkgreen"
  val DarkBlue = "darkblue"
  val DarkCyan = "darkcyan"
  val DarkMagenta = "darkmagenta"
  val LightGrey = "lightgrey"
}

object ColorMaps {
  val Grey = "grey"
  val Blue = "blue"
  val Heat =  "heat"
  val Spectrum2 = "spectrum2"
  val Spectrum2_step = "spectrum2-step"
  val Spectrum = "spectrum"
  val Red = "red"
  val Green = "green"
  val Bluegreen = "bluegreen"
  val Transblack = "transblack"
  val Royal = "royal"
  val Complement = "complement"
  val Cool_Warm = "cool-warm"
  val Green_Magenta = "green-magenta"
  val Blue_Darkred = "blue-darkred"
  val Blue_Darkorange = "blue-darkorange"
  val Brown_Blue = "brown_blue"
  val Blue_Orange= "blue-orange"
  val Seq = "seq"
  val Hot_Desaturated = "hot_desaturated"
  val Yellow_Green = "yellow-green"
  val Yellow_Green_Blue = "yellow-green-blue"
  val Yellow_Orange_Brown = "yellow-orange-brown"
  val Yellow_Orange_Red = "yellow-orange-red"

}