language: scala
dist: trusty
jdk:
  - oraclejdk8

before_install:
  - git fetch --tags
  - sudo add-apt-repository ppa:jeremysanders/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install veusz -y
# in case of "Multiple repositories are found"
  - sbt sonatypeDrop
#  - sbt sonatypeRelease

cache:
  directories:
    - $HOME/.sbt/1.0/dependency
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/launchers
    - $HOME/.ivy2/cache
    - $HOME/.coursier

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - rm -rf $HOME/.ivy2/local

stages:
  - name: test
  - name: release
    if: (branch = master AND type = push) OR (tag IS present)

jobs:
  include:
    # stage="test" if no stage is specified
    - env: TEST="compile"
      script: sbt +compile
    # run ci-release only if previous stages passed
    - stage: release
      script: sbt ci-release