language: scala
dist: trusty
jdk:
- oraclejdk9

before_install:
- git fetch --tags

stages:
- name: test
- name: release
  if: (branch = master AND type = push) OR (tag IS present)

jobs:
  include:
  # stage="test" if no stage is specified
  - env: TEST="compile"
    script: sbt compile
  #- env: TEST="formatting"
   # script: ./bin/scalafmt --test
  # run ci-release only if previous stages passed
  - stage: release
    script: sbt ci-release
